name: k6 load tests

on:
  push:
    branches:
      - k6-pipeline
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start API
        env:
          NODE_ENV: test
          MONGO_URI: mongodb+srv://2023171035:ofBOFh6Ux2Rj4KIS@cluster0.ugps9.mongodb.net/NovaCode?retryWrites=true&w=majority
          JWT_SECRET: test
        run: |
          npm start &
          sleep 15

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gnupg
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 tests
        run: k6 run k6-test.js